on:
  pull_request:
    branches: [ "development" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov=myapp --cov-report=xml:coverage.xml --cov-fail-under=70
      - uses: actions/upload-artifact@v4
        with:
          path: coverage.xml
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building step"